# Generated by Django 2.2.5 on 2019-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_hum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_hi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_light', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_status', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
