# Generated by Django 2.2.5 on 2019-10-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
