# Generated by Django 2.2.5 on 2019-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataplant',
            fields=[
                ('dataplant_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dataplant_date', models.DateTimeField(auto_now=True)),
                ('plant_id', models.CharField(max_length=100)),
                ('plant_hum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_temp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_hi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_light', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plant_status', models.CharField(max_length=100)),
            ],
        ),
    ]
