# Generated by Django 2.2.5 on 2019-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dataplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataplant',
            name='dataplant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
